// this comment tells babel to convert jsx to calls to a function called jsx instead of React.createElement
/** @jsxImportSource @emotion/react */
import { css, jsx } from "@emotion/react";
import Head from "next/head";
import Image from "next/image";
import MainSection from "../components/mainSection";

export default function Home() {
  return (
    <div
      css={css`
        min-height: 100vh;
        padding: 0 0.5rem;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background: #101010;
        height: 100vh;
      `}
    >
      <Head>
        <title>How BurntOut Are You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainSection />
      </main>

      <footer>
        {/* <a
          href="https://www.getairvoice.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image
              src="/airvoice.png"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a> */}
      </footer>
    </div>
  );
}
